#Env:
fix_dir=$(pwd)

#Fixing:
    sudo cp $fix_dir/glib/galloca.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/galloca.h
    sudo cp $fix_dir/glib/gtypes.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gtypes.h
    sudo cp $fix_dir/glib/glibconfig.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/lib/glib-2.0/include/glibconfig.h
    sudo cp $fix_dir/glib/glib.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib.h
    sudo cp $fix_dir/glib/garray.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/garray.h
    sudo cp $fix_dir/glib/gasyncqueue.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gasyncqueue.h
    sudo cp $fix_dir/glib/gthread.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gthread.h
    sudo cp $fix_dir/glib/gatomic.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gatomic.h
    sudo cp $fix_dir/glib/glib-typeof.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/glib-typeof.h
    sudo cp $fix_dir/glib/gquark.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gquark.h
    sudo cp $fix_dir/glib/gutils.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gutils.h
    sudo cp $fix_dir/glib/gbacktrace.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbacktrace.h
    sudo cp $fix_dir/glib/gbase64.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbase64.h
    sudo cp $fix_dir/glib/gbitlock.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbitlock.h
    sudo cp $fix_dir/glib/gbookmarkfile.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbookmarkfile.h
    sudo cp $fix_dir/glib/gbacktrace.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbacktrace.h
    sudo cp $fix_dir/glib/gbase64.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbase64.h
    sudo cp $fix_dir/glib/gbitlock.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbitlock.h
    sudo cp $fix_dir/glib/gdatetime.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gdatetime.h
    sudo cp $fix_dir/glib/gbacktrace.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbacktrace.h
    sudo cp $fix_dir/glib/gbase64.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbase64.h
    sudo cp $fix_dir/glib/gbitlock.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbitlock.h
    sudo cp $fix_dir/glib/gtimezone.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gtimezone.h
    sudo cp $fix_dir/glib/gbytes.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gbytes.h
    sudo cp $fix_dir/glib/gcharset.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gcharset.h
    sudo cp $fix_dir/glib/gchecksum.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gchecksum.h
    sudo cp $fix_dir/glib/gconvert.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gconvert.h
    sudo cp $fix_dir/glib/gdataset.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gdataset.h
    sudo cp $fix_dir/glib/gdate.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gdate.h
    sudo cp $fix_dir/glib/gdir.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gdir.h
    sudo cp $fix_dir/glib/genviron.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/genviron.h
    sudo cp $fix_dir/glib/gfileutils.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gfileutils.h
    sudo cp $fix_dir/glib/ggettext.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/ggettext.h
    sudo cp $fix_dir/glib/ghash.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/ghash.h
    sudo cp $fix_dir/glib/ghmac.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/ghmac.h
    sudo cp $fix_dir/glib/ghook.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/ghook.h
    sudo cp $fix_dir/glib/ghostutils.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/ghostutils.h
    sudo cp $fix_dir/glib/giochannel.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/giochannel.h
    sudo cp $fix_dir/glib/gkeyfile.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gkeyfile.h
    sudo cp $fix_dir/glib/gmappedfile.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gmappedfile.h
    sudo cp $fix_dir/glib/gmarkup.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gmarkup.h
    sudo cp $fix_dir/glib/gmem.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gmem.h
    sudo cp $fix_dir/glib/gmessages.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gmessages.h
    sudo cp $fix_dir/glib/gnode.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gnode.h
    sudo cp $fix_dir/glib/goption.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/goption.h
    sudo cp $fix_dir/glib/gpathbuf.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gpathbuf.h
    sudo cp $fix_dir/glib/gpattern.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gpattern.h
    sudo cp $fix_dir/glib/gpoll.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gpoll.h
    sudo cp $fix_dir/glib/gprimes.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gprimes.h
    sudo cp $fix_dir/glib/gqsort.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gqsort.h
    sudo cp $fix_dir/glib/gqueue.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gqueue.h
    sudo cp $fix_dir/glib/grand.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/grand.h
    sudo cp $fix_dir/glib/grcbox.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/grcbox.h
    sudo cp $fix_dir/glib/grefcount.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/grefcount.h
    sudo cp $fix_dir/glib/grefstring.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/grefstring.h
    sudo cp $fix_dir/glib/gscanner.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gscanner.h
    sudo cp $fix_dir/glib/gsequence.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gsequence.h
    sudo cp $fix_dir/glib/gshell.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gshell.h
    sudo cp $fix_dir/glib/gslice.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gslice.h
    sudo cp $fix_dir/glib/gslist.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gslist.h
    sudo cp $fix_dir/glib/gspawn.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gspawn.h
    sudo cp $fix_dir/glib/gstrfuncs.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gstrfuncs.h
    sudo cp $fix_dir/glib/gstringchunk.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gstringchunk.h
    sudo cp $fix_dir/glib/gstring.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gstring.h
    sudo cp $fix_dir/glib/gstrvbuilder.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gstrvbuilder.h
    sudo cp $fix_dir/glib/gtestutils.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gtestutils.h
    sudo cp $fix_dir/glib/gthreadpool.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gthreadpool.h
    sudo cp $fix_dir/glib/gtimer.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gtimer.h
    sudo cp $fix_dir/glib/gtrashstack.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gtrashstack.h
    sudo cp $fix_dir/glib/gtree.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gtree.h
    sudo cp $fix_dir/glib/gunicode.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gunicode.h
    sudo cp $fix_dir/glib/guri.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/guri.h
    sudo cp $fix_dir/glib/guuid.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/guuid.h
    sudo cp $fix_dir/glib/gvariant.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gvariant.h
    sudo cp $fix_dir/glib/gvarianttype.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gvarianttype.h
    sudo cp $fix_dir/glib/gversion.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gversion.h
    sudo cp $fix_dir/glib/glist.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/glist.h
    sudo cp $fix_dir/glib/gmain.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/gmain.h
    sudo cp $fix_dir/glib/gallocator.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/deprecated/gallocator.h
    sudo cp $fix_dir/glib/gcache.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/deprecated/gcache.h
    sudo cp $fix_dir/glib/gcompletion.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/deprecated/gcompletion.h
    sudo cp $fix_dir/glib/gmain-dep.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/deprecated/gmain.h
    sudo cp $fix_dir/glib/grel.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/deprecated/grel.h
    sudo cp $fix_dir/glib/gthread-dep.h $working_dir/PKGCONFIG/pango-cairo-wasm/build/include/glib-2.0/glib/deprecated/gthread.h


